name: Action
description: A concrete action linked to an Idea or Bug
type: Task
labels: ["action"]
projects: ["metatrom-ag/6"]
body:
  - type: markdown
    attributes:
      value: |
        ## Action (What)
        Create this as a **sub-issue** from a parent Issue.

  - type: textarea
    id: description
    attributes:
      label: Action Description
      description: What needs to be done? (optional for small tasks)
      placeholder: Describe the concrete action
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this action is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Relative complexity/effort
      options:
        - "1 - Trivial"
        - "2 - Small"
        - "3 - Medium"
        - "5 - Large"
        - "8 - Very Large"
    validations:
      required: true
