name: Bug Report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Critical - System unusable"
        - "High - Major feature broken"
        - "Medium - Feature impaired"
        - "Low - Minor issue"
    validations:
      required: true

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Relative complexity/effort to fix (if known)
      options:
        - "1 - Trivial"
        - "2 - Small"
        - "3 - Medium"
        - "5 - Large"
        - "8 - Very Large"
        - "13 - Epic (needs breakdown)"
        - "Unknown"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      placeholder: "e.g., Production, Staging, Local dev"
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Relevant system info (OS, browser, version, etc.)
      placeholder: |
        - OS: macOS 14.0
        - Browser: Chrome 120
        - App Version: 1.2.3
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Any relevant logs, error messages, or screenshots
      placeholder: Paste logs or drag & drop screenshots here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context here
    validations:
      required: false
