name: Idea / Feature Request
description: Suggest a new idea or feature
type: Feature
labels: ["idea", "enhancement"]
projects: ["metatrom-ag/6"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ontocratic Issue Creation
        Define the **Purpose** (Why) and **Intention** (How) clearly.
        Actions (What) will be created as sub-issues once this is refined.

  - type: textarea
    id: purpose
    attributes:
      label: Purpose (Why)
      description: |
        The reason this exists. How does it connect to our goals/strategy?
        What problem does it solve? Why does this matter?
      placeholder: |
        This exists because...
        It connects to our goal of...
    validations:
      required: true

  - type: textarea
    id: intention
    attributes:
      label: Intention (How)
      description: |
        How do you envision approaching this?
        What is the communication of this purpose to the team?
      placeholder: |
        We will approach this by...
        The key aspects are...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Actions (What)
        Once this idea is refined, create **sub-issues** for concrete actions.
        Use the issue sidebar → "Create sub-issue" to link actions to this idea.

  - type: textarea
    id: initial-actions
    attributes:
      label: Initial Actions (optional)
      description: |
        Draft potential actions. These can become sub-issues later.
      placeholder: |
        - [ ] Action 1
        - [ ] Action 2
        - [ ] Action 3
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### Feedback (Reality)
        Feedback will emerge through reviews, discussions, and retrospectives.

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria / Feedback Mechanism
      description: |
        How will we know this is successful?
        What measurements or feedback loops should be in place?
      placeholder: |
        Success looks like...
        We will measure by...
    validations:
      required: false

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Relative complexity/effort
      options:
        - "1 - Trivial"
        - "2 - Small"
        - "3 - Medium"
        - "5 - Large"
        - "8 - Very Large"
        - "13 - Epic (needs breakdown)"
        - "Unknown"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this idea?
      options:
        - "Low - Nice to have"
        - "Medium - Should have"
        - "High - Must have"
    validations:
      required: false
