name: Idea / Feature Request
description: Suggest a new idea or feature
type: Feature
labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your idea!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the idea or feature
      placeholder: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is this needed?
      placeholder: Describe the problem or motivation behind this idea
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
      placeholder: Describe your proposed solution
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: Describe alternatives you've considered
    validations:
      required: false

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Relative complexity/effort (if known)
      options:
        - "1 - Trivial"
        - "2 - Small"
        - "3 - Medium"
        - "5 - Large"
        - "8 - Very Large"
        - "13 - Epic (needs breakdown)"
        - "Unknown"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this idea?
      options:
        - "Low - Nice to have"
        - "Medium - Should have"
        - "High - Must have"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or screenshots
      placeholder: Add any other context here
    validations:
      required: false
