name: Auto-assign actions
on:
  issues:
    types: [opened]

jobs:
  assign:
    if: |
      contains(github.event.issue.labels.*.name, 'action') &&
      github.event.issue.assignees[0] == null
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.event.issue.user.login }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
